### ISSUE TITLE
Fixed

### ISSUE THREAD

**Issue by archmord** [leandrovieiraa/ytubebot#2]
`python app.py

[1;36;40m ========== YTubeBOT ========== [0m

[1;32;40m [ OK ] [0m: [1;33;40m2019-09-22:20:45:07 [0m - Initializing system.
[1;32;40m [ OK ] [0m: [1;33;40m2019-09-22:20:45:07 [0m - Initializing watcher with async instances count: 1
[1;32;40m [ OK ] [0m: [1;33;40m2019-09-22:20:45:07 [0m - Playlist data loaded successfully.
[1;32;40m [ OK ] [0m: [1;33;40m2019-09-22:20:45:07 [0m - Initializing controllers

DevTools listening on ws://127.0.0.1:50037/devtools/browser/5a1ea1d5-c0a5-4e75-95c9-b5b5f0de562e
Task exception was never retrieved
future: <Task finished coro=<Controller.start_controller() done, defined at C:\Users\User\github\ytubebot\controller.py:7> exception=SessionNotCreatedException('session not created: Chrome version must be between 70 and 73\n  (Driver info: chromedriver=73.0.3683.20 (8e2b610813e167eee3619ac4ce6e42e3ec622017),platform=Windows NT 10.0.18362 x86_64)', None, None)>
Traceback (most recent call last):
  File "C:\Users\User\github\ytubebot\controller.py", line 21, in start_controller
    driver = webdriver.Chrome(chrome_options=options, executable_path=r'./driver/chromedriver.exe')
  File "C:\Python\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "C:\Python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Python\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome version must be between 70 and 73
  (Driver info: chromedriver=73.0.3683.20 (8e2b610813e167eee3619ac4ce6e42e3ec622017),platform=Windows NT 10.0.18362 x86_64)

[1;36;40m
 =========== Finish =========== [0m`

**Comment by ElectroGamesDev** [comment]
ERROR: Command errored out with exit status 1:
     command: 'c:\users\tristyn\appdata\local\programs\python\python38-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Tristyn\\AppData\\Local\\Temp\\pip-install-vteg3a32\\typed-ast\\setup.py'"'"'; __file__='"'"'C:\\Users\\Tristyn\\AppData\\Local\\Temp\\pip-install-vteg3a32\\typed-ast\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Tristyn\AppData\Local\Temp\pip-record-gfha1pbd\install-record.txt' --single-version-externally-managed --compile
         cwd: C:\Users\Tristyn\AppData\Local\Temp\pip-install-vteg3a32\typed-ast\
    Complete output (13 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-3.8
    creating build\lib.win32-3.8\typed_ast
    copying typed_ast\ast27.py -> build\lib.win32-3.8\typed_ast
    copying typed_ast\ast3.py -> build\lib.win32-3.8\typed_ast
    copying typed_ast\conversions.py -> build\lib.win32-3.8\typed_ast
    copying typed_ast\__init__.py -> build\lib.win32-3.8\typed_ast
    running build_ext
    building '_ast27' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\tristyn\appdata\local\programs\python\python38-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Tristyn\\AppData\\Local\\Temp\\pip-install-vteg3a32\\typed-ast\\setup.py'"'"'; __file__='"'"'C:\\Users\\Tristyn\\AppData\\Local\\Temp\\pip-install-vteg3a32\\typed-ast\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Tristyn\AppData\Local\Temp\pip-record-gfha1pbd\install-record.txt' --single-version-externally-managed --compile Check the logs for full command output.

:/

**Comment by archmord** [comment]
Fixed
